### PR TITLE
Will not overwrite status if it is not successful.

### PR DESCRIPTION
**Pull request by libook**
I found an issue:
If there is any problem with request parameters. I wish to respond some error message and a "400" status to client.
But koa-pagination will always overwrite the status code to "206" if there is "Range" header in the request. Means the response status is controlled by client. That seems not be a good solution.

My solution is(may not be the best):
Only when the response status is in the range of "successful", koa-pagination will overwrite the status code to "206" if there is "Range" header in the request.
According to RFC 2616, status code "2xx" means "successful". https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

### CODE REVIEW

**Comment by libook** [comment]
@ruimarinho Have a look?

**Comment by libook** [comment]
@ruipenso @nunofgs @kurayama @ruimarinho @fixe Have a look?

**Comment by nunofgs** [comment]
@libook thank you for the contribution! Unfortunately time has been short but we'll take a look at this PR very soon. Thanks again!

**Comment by franciscocardoso** [comment]
Hi @libook,

If you want to return an error `400` you should throw an error _(code 400)_ instead of changing the `ctx.status`:

```js
app.use(ctx => {
  const error = new Error();

  error.status = 400;

  throw error;
  
  // Instead of this.
  // ctx.status = 400;
 });
```

Have you tried this approach? It should wield the result you want.

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by libook** [comment]
Hi @franciscocardoso ,

### Yes, this could work.

Throwing an error will jump out from current request processing. 
So the remaining code of this midware would not be executed. 
And the error will be handled by Koa or outer midwares.

### Well, koa provided the 'ctx.status' way.

The code I contributed will support the 'ctx.status' way without breaking the 'throwing error' way.
This could be a better solution than refusing to use 'ctx.status' with this midware. What do you think?

**Comment by nunofgs** [comment]
Thanks. Landed in [064ffb8](https://github.com/uphold/koa-pagination/commit/064ffb83421637dd248b83e5524774450c935875).

**Pull request closed without merging**
